### Возмущение корреляционной матрицы

In [ ]:
import numpy as np
import scipy as sp
import matplotlib as plt
from numpy import linalg

#### (а)

In [ ]:
C = np.asarray([[1, 0.9, 0.7], [0.9, 1, 0.4], [0.7, 0.4, 1]])
print('Собственные значения C: \n', linalg.eig(C)[0])

Собственные значения C: 
 [2.35363603 0.03034736 0.6160166 ]


In [ ]:
C_0 = np.asarray([[1, 0.9, 0.7], [0.9, 1, 0.3], [0.7, 0.3, 1]])
eigvalues_C0, eigvector_C0 = linalg.eig(C_0)
print('Собственные значения C_0:\n', eigvalues_C0)
print('Собственные вектора C_0:\n', eigvector_C0)

Собственные значения C_0:
 [ 2.29672779 -0.00735244  0.71062465]
Собственные вектора C_0:
 [[ 0.65991684  0.74767038 -0.0741536 ]
 [ 0.57099598 -0.5632171  -0.5972856 ]
 [ 0.48833733 -0.35181742  0.79859323]]


In [ ]:
#Ввести новые с.з. по правилу
eigvalues_C0[eigvalues_C0 < 0] = 0

#Умножить с.в. si на модифицированные с.з. λ и использовать их в качестве столбцов новой матрицы
B = eigvector_C0 * np.sqrt(eigvalues_C0)

#Отнормировать строки матрицы B0 (вектора) на единичную длину, получив тем самым новую матрицу B.
B = B / linalg.norm(B, axis=1).reshape(-1,1)

#Построить новую возмущенную корреляционную матрицу по правилу C_1 = B B^T
C_1 = B @ B.T
print('Новая возмущенная корреляционная матрица C1:\n', C_1)
print('\n', 'Собственные значения новой корреляционной C1:\n', np.linalg.eig(C_1)[0])

Новая возмущенная корреляционная матрица C1:
 [[1.         0.89402441 0.69631907]
 [0.89402441 1.         0.30096904]
 [0.69631907 0.30096904 1.        ]]

 Собственные значения новой корреляционной C1:
 [ 2.29039373e+00 -3.29597460e-17  7.09606272e-01]


#### На диагонали матрицы $C_1$ стоят 1, так как в процессе построения строки матрицы $B'$ нормируются, а затем происходит умножение полученной матрицы $B$ на $B^T$.
#### 
#### Также, она явлется положительно определенной. Доказательство: 
#### SVD разложение матрицы $B$: $B=U\Sigma{V^T} $
#### $C_1 = BB^T = U\Sigma V^T(U\Sigma V^T)^T=U\Sigma V^T V\Sigma^{-1}U^T = U\Sigma^2U^T$
#### Матрица является положительно определенной, если ее собственные значения $\lambda_i>0$
#### Собственные значения $\Sigma^2$ по определению больше 0. 
#### Умножение слева на $U$ и справа на $U^T$ будет переходом к новому базису, что не меняет собственные значения. 
#### Следовательно, матрица $C_1$ является положительно определенной.

### Сравним $C_1$ и $C_0$:

In [ ]:
print('C1:\n', C_1)
print('C0:\n', C_0)

C1:
 [[1.         0.89402441 0.69631907]
 [0.89402441 1.         0.30096904]
 [0.69631907 0.30096904 1.        ]]
C0:
 [[1.  0.9 0.7]
 [0.9 1.  0.3]
 [0.7 0.3 1. ]]


#### Рандомный пример:

In [ ]:
new_C = np.asarray([[1, 0.7, 0.5], [0.7, 1, 0.2], [0.5, 0.2, 1]])
print(new_C)

[[1.  0.7 0.5]
 [0.7 1.  0.2]
 [0.5 0.2 1. ]]


In [ ]:
print('Собственные значения new_C: \n', linalg.eig(new_C)[0])

Собственные значения new_C: 
 [1.96204151 0.22596542 0.81199307]


In [ ]:
#### Поменяем 0.2 на 0.3

In [ ]:
new_C0 = np.asarray([[1, 0.7, 0.5], [0.7, 1, 0.3], [0.5, 0.2, 1]])
eigvalues_new_C0, eigvector_new_C0 = linalg.eig(new_C0)
print('Собственные значения C_0:\n', eigvalues_new_C0)
print('Собственные вектора C_0:\n', eigvector_new_C0)

Собственные значения C_0:
 [1.98845532 0.2465098  0.76503488]
Собственные вектора C_0:
 [[ 0.65636531  0.7516462  -0.17619041]
 [ 0.60259518 -0.5587496  -0.53230034]
 [ 0.45394231 -0.35046664  0.82801768]]


In [ ]:
#Ввести новые с.з. по правилу
eigvalues_new_C0[eigvalues_new_C0 < 0] = 0

#Умножить с.в. si на модифицированные с.з. λ и использовать их в качестве столбцов новой матрицы
newB = eigvector_new_C0 * np.sqrt(eigvalues_new_C0)

#Отнормировать строки матрицы B0 (вектора) на единичную длину, получив тем самым новую матрицу B.
newB = newB / linalg.norm(newB, axis=1).reshape(-1,1)

#Построить новую возмущенную корреляционную матрицу по правилу C_1 = B B^T
newC_1 = newB @ newB.T
print('Новая возмущенная корреляционная матрица new_C1:\n', newC_1)
print('\n', 'Собственные значения новой корреляционной C1:\n', np.linalg.eig(newC_1)[0])

Новая возмущенная корреляционная матрица new_C1:
 [[1.         0.74155427 0.41938612]
 [0.74155427 1.         0.25762911]
 [0.41938612 0.25762911 1.        ]]

 Собственные значения новой корреляционной C1:
 [1.97777627 0.23702175 0.78520198]


In [ ]:
#### Работает. 